/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f401re_gpio.h>
#include <stm32f401re_rcc.h>

#define LOW                      0
#define BTN_PRESS                LOW
#define GPIO_PIN_SET             1
#define GPIO_PIN_RESET           0

// LED xanh (PA5)
#define LED_GREEN_PORT           GPIOA
#define LED_GREEN_PIN            GPIO_Pin_5
#define LEDGREEN_SetClock        RCC_AHB1Periph_GPIOA

// LED RED1 (PA1)
#define LED_RED1_PORT            GPIOA
#define LED_RED1_PIN             GPIO_Pin_1
#define LEDRED1_SetClock         RCC_AHB1Periph_GPIOA

// LED RED2 (PB13) → được B4 điều khiển
#define LED_RED2_PORT            GPIOB
#define LED_RED2_PIN             GPIO_Pin_13
#define LEDRED2_SetClock         RCC_AHB1Periph_GPIOB

// LED BLUE1 (PA3)
#define LED_BLUE1_PORT           GPIOA
#define LED_BLUE1_PIN            GPIO_Pin_3
#define LEDBLUE1_SetClock        RCC_AHB1Periph_GPIOA

// LED BLUE2 (PA10)
#define LED_BLUE2_PORT           GPIOA
#define LED_BLUE2_PIN            GPIO_Pin_10
#define LEDBLUE2_SetClock        RCC_AHB1Periph_GPIOA

// Buzzer (PC9)
#define BUZZER_PORT              GPIOC
#define BUZZER_PIN               GPIO_Pin_9
#define BUZZER_SetClock          RCC_AHB1Periph_GPIOC

// Button B3 (PA4)
#define BUTTON3_PORT             GPIOA
#define BUTTON3_PIN              GPIO_Pin_4
#define BUTTON3_SetClock         RCC_AHB1Periph_GPIOA

// Button B4 (PB0)
#define BUTTON4_PORT             GPIOB
#define BUTTON4_PIN              GPIO_Pin_0
#define BUTTON4_SetClock         RCC_AHB1Periph_GPIOB

void delay_ms(uint32_t time) {
	for (uint32_t i = 0; i < time * 3000; i++);
}

void init_GPIO_output(GPIO_TypeDef *port, uint16_t pin, uint32_t clock) {
	GPIO_InitTypeDef GPIO_InitStruct;
	RCC_AHB1PeriphClockCmd(clock, ENABLE);
	GPIO_InitStruct.GPIO_Pin = pin;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_OUT;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(port, &GPIO_InitStruct);
}

void init_GPIO_input(GPIO_TypeDef *port, uint16_t pin, uint32_t clock) {
	GPIO_InitTypeDef GPIO_InitStruct;
	RCC_AHB1PeriphClockCmd(clock, ENABLE);
	GPIO_InitStruct.GPIO_Pin = pin;
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_Init(port, &GPIO_InitStruct);
}

static void LedControl_SetStatus(GPIO_TypeDef *GPIOx, uint16_t GPIO_PIN, uint8_t Status) {
	if (Status == GPIO_PIN_SET)
		GPIOx->BSRRL = GPIO_PIN;
	else
		GPIOx->BSRRH = GPIO_PIN;
}

static uint8_t ButtonRead_Status(GPIO_TypeDef *GPIOx, uint16_t GPIO_PIN) {
	return ((GPIOx->IDR & GPIO_PIN) != Bit_RESET) ? 1 : 0;
}

int main(void) {
	uint8_t b3_press_count = 0;
	uint8_t b4_prev = 1, b4_toggle = 0;

	// Khởi tạo output
	init_GPIO_output(LED_GREEN_PORT, LED_GREEN_PIN, LEDGREEN_SetClock);
	init_GPIO_output(LED_RED1_PORT, LED_RED1_PIN, LEDRED1_SetClock);
	init_GPIO_output(LED_RED2_PORT, LED_RED2_PIN, LEDRED2_SetClock);  // ← LED2 RED
	init_GPIO_output(LED_BLUE1_PORT, LED_BLUE1_PIN, LEDBLUE1_SetClock);
	init_GPIO_output(LED_BLUE2_PORT, LED_BLUE2_PIN, LEDBLUE2_SetClock);
	init_GPIO_output(BUZZER_PORT, BUZZER_PIN, BUZZER_SetClock);

	// Khởi tạo input
	init_GPIO_input(BUTTON3_PORT, BUTTON3_PIN, BUTTON3_SetClock);
	init_GPIO_input(BUTTON4_PORT, BUTTON4_PIN, BUTTON4_SetClock);

	// 1. Nháy LED xanh khi khởi động
	for (int i = 0; i < 2; i++) {
		LedControl_SetStatus(LED_GREEN_PORT, LED_GREEN_PIN, GPIO_PIN_SET);
		delay_ms(200);
		LedControl_SetStatus(LED_GREEN_PORT, LED_GREEN_PIN, GPIO_PIN_RESET);
		delay_ms(200);
	}

	while (1) {
		// 2. Nhấn B3 hai lần → nháy 2 RED + 2 BLUE + buzzer
		if (ButtonRead_Status(BUTTON3_PORT, BUTTON3_PIN) == BTN_PRESS) {
			b3_press_count++;
			while (ButtonRead_Status(BUTTON3_PORT, BUTTON3_PIN) == BTN_PRESS);
			delay_ms(50);

			if (b3_press_count == 2) {
				for (int i = 0; i < 2; i++) {
					LedControl_SetStatus(LED_RED1_PORT, LED_RED1_PIN, GPIO_PIN_SET);
					LedControl_SetStatus(LED_RED2_PORT, LED_RED2_PIN, GPIO_PIN_SET);
					LedControl_SetStatus(LED_BLUE1_PORT, LED_BLUE1_PIN, GPIO_PIN_SET);
					LedControl_SetStatus(LED_BLUE2_PORT, LED_BLUE2_PIN, GPIO_PIN_SET);
					LedControl_SetStatus(BUZZER_PORT, BUZZER_PIN, GPIO_PIN_SET);
					delay_ms(200);

					LedControl_SetStatus(LED_RED1_PORT, LED_RED1_PIN, GPIO_PIN_RESET);
					LedControl_SetStatus(LED_RED2_PORT, LED_RED2_PIN, GPIO_PIN_RESET);
					LedControl_SetStatus(LED_BLUE1_PORT, LED_BLUE1_PIN, GPIO_PIN_RESET);
					LedControl_SetStatus(LED_BLUE2_PORT, LED_BLUE2_PIN, GPIO_PIN_RESET);
					LedControl_SetStatus(BUZZER_PORT, BUZZER_PIN, GPIO_PIN_RESET);
					delay_ms(200);
				}
				b3_press_count = 0;
			}
		}

		// 3. Nhấn B4 để bật/tắt LED2 đỏ (PB14)
		uint8_t b4_current = ButtonRead_Status(BUTTON4_PORT, BUTTON4_PIN);
		if (b4_current == BTN_PRESS && b4_prev != BTN_PRESS) {
			b4_toggle = !b4_toggle;
			LedControl_SetStatus(LED_RED2_PORT, LED_RED2_PIN, b4_toggle ? GPIO_PIN_SET : GPIO_PIN_RESET);
			delay_ms(50);
		}
		b4_prev = b4_current;
	}
}
